---
# Pinned to detect changes at playbook runtime

- name: Hostname is set
  ansible.builtin.hostname:
    name: channa-homelab

- name: Timezone is UTC
  community.general.timezone:
    name: Etc/UTC

# Motivates `live-restore` in daemon.json
- name: Unattended upgrades installed
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Unattended upgrades enabled
  ansible.builtin.systemd_service:
    name: unattended-upgrades
    enabled: true
    state: started
